title = "Kreee's Blog"
baseURL = "https://blog.ohmykreee.top"

# Option 1 (recommended): adding the theme as a Hugo module
# theme = "github.com/Lednerb/bilberry-hugo-theme/v4"


# Options 2 and 3: cloning/copying the theme files
theme = "bilberry-hugo-theme/v4"

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages defined at the end.
DefaultContentLanguage = "zh-cn"

# Enable / Disable Google Analytics statistics for your site
# googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

[params]
  enableLightDarkTheme = true

  # Custom CSS/JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = ['https://unpkg.com/cookieconsent@3/build/cookieconsent.min.css']
  js_modules = ['https://unpkg.com/cookieconsent@3/build/cookieconsent.min.js', '/js/init-cookieconsent.js', '/js/clarity-tracker.js', '/js/init-sakana.js']

  # Description and meta data for the search engines
  author = "Kreee"
  description = "A Kreee's Blog, powered by GitHub Pages, Hugo and Bilberry Premium Theme for Hugo."
  keywords = "kreee,blog,personal,responsive,search,font awesome,pages,posts,syntax highlighting,shortcuts"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "BYCFQKEA4W"
  algolia_apiKey    = "5b8f1a1d7557fc3b1bc0d99efbaa22ce"
  algolia_indexName = "kreee-blog"
  # Set this option to false if you want to search within all articles in all languages at once
  algolia_currentLanguageOnly = false

  # Enable / Disable comments on the articles via commento
  # commentoJsURL = "https://commento.lednerb.de/js/commento.js"

  # Enable / Disable Giscus comments
  giscus             = true
  giscusJsUrl        = "https://giscus.app/client.js"
  giscusRepository   = "ohmykreee/kreee-blog"
  giscusRepositoryId = "MDEwOlJlcG9zaXRvcnkzNzQxMjE4ODE="
  giscusMapping      = "og:title"
  giscusCategory     = "Comments"
  giscusCategoryId   = "DIC_kwDOFkylmc4B_6vB"
  giscusTheme        = "light"
  giscusReactions    = "1"
  giscusEmitMetadata = "0"
  giscusLanguage     = "zh-CN"
  giscusCrossOrigin  = "anonymous"

  # Enable / Disable Utterances comments
  utterances            = false
  utterancesJsUrl       = "https://utteranc.es/client.js"
  utterancesRepository  = "[ENTER REPO HERE]"
  utterancesIssueTerm   = "pathname"
  utterancesLabel       = "Comment"
  utterancesTheme       = "github-light"
  utterancesCrossOrigin = "anonymous"

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Code with love ❤ and paws 🐾!"

    # if you want to use libravatar or gravatar for the header image
    avatarEmail = ""

    # set an path to the image file you want to use | overwrites avatar by email
    customImage = "https://avatars.githubusercontent.com/u/76862878"

    # define the icon you want to use for the overlay for the customImage or avatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = true

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = false

    # show a language chooser in the header
    showHeaderLanguageChooser = false

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    pinnedPost = "/status/fav-music/"
    # Set to true to pin only to the first page, false to all pages
    pinOnlyToFirstPage = true

    # enable automatic localization of the article's published date using Moment.js
    enableMomentJs = true

    # customize the date format | only works if Moment.js is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = false

    # Minimum word count to display the Table of Contents
    tocMinWordCount = 400

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 7

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 7

    # show a language chooser in the footer
    showFooterLanguageChooser = false

    # social media profile urls for the footer links
    showSocialMedia = true

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      { link = "https://github.com/ohmykreee", icon = "fab fa-github", rel = "me" },
      { link = "https://twitter.com/kre_pow3", icon = "fab fa-twitter", rel = "me"  },
      { link = "https://space.bilibili.com/361507684", icon = "fab fa-bilibili", rel = "me"  },
      { link = "https://www.ohmykreee.top", icon = "fas fa-globe", rel = "me"  },
    ]

    # show an archive link in the footer
    showArchive = false

    # archive grouping: "2006" by year, "2006-01" by month
    archiveDateGrouping = "2006-01"

    # credits line configuration
    copyrightBy = "by Kreee"
    copyrightUseCurrentYear = false  # set to true to always display the current year in the copyright
    copyrightYearOverride = "CC BY-NC 4.0"
    copyrightUrl = "https://github.com/ohmykreee"
    creditsText = "Bilberry Hugo Theme"
    creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"


# customize your available languages for your multi-lingual site
# or delete one of the [Languages.xx] blocks to use the theme with only one supported language
[Languages]
  [Languages.zh-cn]
    weight = 1
  # [Languages.de]
  #   weight = 2
  #   title = "Mein cooler neuer Blog"
  #   subtitle = "Hallo Welt! Dies ist der epischste Untertitel aller Zeiten."

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      # change to 'true' if you need to render raw HTML within your markdown content
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    # hl_Lines = ''
    # hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

# do NOT change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
  series   = "series"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]