{
 "title": "OPNsense Filter",
 "description": "A dashboard that visualizes filter logs from pfSense and OPNsense using regex parsing.",
 "tags": [
  "network",
  "opnsense"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource_loki", "label": "Data Source", "query": "loki" },
   {
    "name": "hostname",
    "label": "Instance",
    "query": {}
   },
   {
    "name": "regexipv4",
    "query": "(?i)^(?P<rule>\\w+),\\w?,\\w?,(?P<tracker>\\w+),(?P<interface>[\\w\\.]+),\\w+,(?P<action>\\w+),(?P<direction>\\w+),(?P<ipversion>4),\\w+,\\w*,\\w+,\\w+,\\w+,\\w+,\\w+,(?P<protocol>tcp|udp),\\w+,(?P<srcip>([\\w\\.\\:]+)),(?P<dstip>([\\w\\.\\:]+)),(?P<srcport>\\w+),(?P<dstport>\\w+),\\w+(,?(?P<flags>\\w+))?"
   },
   {
    "name": "regexNonProto",
    "query": "^(?P<rule>\\w+),\\w?,\\w?,(?P<tracker>\\w+),(?P<interface>[\\w\\.]+),\\w+,(?P<action>\\w+),(?P<direction>\\w+),(?P<ipversion>\\d)"
   },
   {
    "name": "regexipv6",
    "query": "(?i)^(?P<rule>\\w+),\\w?,\\w?,(?P<tracker>\\w+),(?P<interface>[\\w\\.]+),\\w+,(?P<action>\\w+),(?P<direction>\\w+),(?P<ipversion>6),\\w+,\\w+,\\w+,(?P<protocol>tcp|udp),\\w+,\\w+,(?P<srcip>([\\w\\.\\:]+)),(?P<dstip>([\\w\\.\\:]+)),(?P<srcport>\\w+),(?P<dstport>\\w+),\\w+(,?(?P<flags>\\w+))?"
   },
   {
    "name": "regexcarp",
    "query": "(?i)^(?P<rule>\\w+),\\w?,\\w?,(?P<tracker>\\w+),(?P<interface>[\\w\\.]+),\\w+,(?P<action>\\w+),(?P<direction>\\w+),(?P<ipversion>\\d),\\w+,\\w*,\\w+,\\w+,\\w+,\\w+,\\w+,(?P<protocol>carp),\\w+,(?P<srcip>([\\w\\.\\:]+)),(?P<dstip>([\\w\\.\\:]+))"
   },
   {
    "name": "interval",
    "label": "Timeline Interval",
    "query": "1s,2s,5s,10s,15s,30s,45s,1m,2m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Action timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(action) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexNonProto` | ipversion > 0 | action =~ `.+` [$__interval]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Packets by action",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(action) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexNonProto` | ipversion > 0 | action =~ `.+` [$__range]))",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Actions by rule",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(rule) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexNonProto` | ipversion > 0 | action =~ `.+`   [$__range]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Packets by interface",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(interface) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexNonProto` | ipversion > 0 [$__range]))",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Packets by IP version",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ipversion) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexNonProto` | ipversion =~ `\\d` [$__range]))",
     "legendFormat": "IPv{{ipversion}}"
    }
   ]
  },
  {
   "title": "Packets by protocol",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(protocol) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `(?i)$regexNonProto,\\w+,\\w+,\\w+,(?P<protocol>tcp|udp)` | regexp `(?i)$regexNonProto,\\w+,\\w*,\\w+,\\w+,\\w+,\\w+,\\w+,(?P<protocol>tcp|udp|carp)` | ipversion > 0 | label_format protocol=\"{{.protocol | ToLower }}\" [$__range]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Packets by IP version/protocol",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(protocol, ipversion) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `(?i)$regexNonProto,\\w+,\\w+,\\w+,(?P<protocol>tcp|udp)` | regexp `(?i)$regexNonProto,\\w+,\\w*,\\w+,\\w+,\\w+,\\w+,\\w+,(?P<protocol>tcp|udp|carp)` | ipversion > 0 | label_format protocol=\"{{.protocol | ToLower }}\" [$__range]))",
     "legendFormat": "IPv{{ipversion}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Top source IPs",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(srcip) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexipv4` | ipversion = `4` [$__range]))",
     "legendFormat": "{{srcip}}"
    },
    {
     "expr": "sum by(srcip) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexipv6` | ipversion = `6` [$__range]))",
     "legendFormat": "{{srcip}}"
    },
    {
     "expr": "sum by(srcip) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexcarp` | protocol = `carp` [$__range]))",
     "legendFormat": "{{srcip}}"
    }
   ]
  },
  {
   "title": "Top destination IPs",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dstip) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexipv4` | ipversion = `4` [$__range]))",
     "legendFormat": "{{dstip}}"
    },
    {
     "expr": "sum by(dstip) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexipv6` | ipversion = `6` [$__range]))",
     "legendFormat": "{{dstip}}"
    },
    {
     "expr": "sum by(dstip) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexcarp` | protocol = `carp` [$__range]))",
     "legendFormat": "{{dstip}}"
    }
   ]
  },
  {
   "title": "Top destination ports",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(dstport) (count_over_time({hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexipv4` | regexp `$regexipv6` | ipversion > 0 [$__range]))",
     "legendFormat": "{{ipversion}} {{dstport}}"
    }
   ]
  },
  {
   "title": "src_ip Locations",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "panelId": 8 }
   ]
  },
  {
   "title": "dest_ip Locations",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 35 },
   "targets": [
    { "panelId": 8 }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Filter Log",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "{hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexipv4` | ipversion = `4`"
    },
    {
     "expr": "{hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexipv6` | ipversion = `6` | label_format protocol=\"{{.protocol | ToLower }}\""
    },
    {
     "expr": "{hostname=~\"$hostname\", app=\"filterlog\"} | regexp `$regexcarp` | protocol = `carp`"
    }
   ]
  }
 ]
}