{
 "title": "OPNSense IDS/IPS",
 "tags": [
  "network",
  "opnsense"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_loki", "label": "Data Source", "query": "loki" },
   {
    "name": "hostname",
    "query": {}
   },
   {
    "name": "interval",
    "label": "Timeline Interval",
    "query": "1s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Action timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(sumby) (count_over_time({app=\"suricata\", hostname=~\"$hostname\"} | json event_type=\"event_type\", ip_version=\"ip_v\", sumby=\"alert.action\" | __error__=`` | event_type =~ `.+` | ip_version > 0 [$__interval]))"
    }
   ]
  },
  {
   "title": "Allowed Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"suricata\", hostname=~\"$hostname\"} | json event_type=\"event_type\", ip_version=\"ip_v\", sumby=\"alert.action\" | __error__=`` | sumby = `allowed` | ip_version > 0 [$__range]))"
    }
   ]
  },
  {
   "title": "Blocked Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"suricata\", hostname=~\"$hostname\"} | json event_type=\"event_type\", ip_version=\"ip_v\", sumby=\"alert.action\" | __error__=`` | sumby = `blocked` | ip_version > 0 [$__range]))"
    }
   ]
  },
  {
   "title": "Potential Attacks",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(sumby) (count_over_time({app=\"suricata\", hostname=~\"$hostname\"} | json event_type=\"event_type\", ip_version=\"ip_v\", sumby=\"app_proto\" | __error__=`` | event_type =~ `.+` | ip_version > 0 [$__range]))"
    }
   ]
  },
  {
   "title": "Potential Attacks From",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(sumby) (count_over_time({app=\"suricata\", hostname=~\"$hostname\"} | json event_type=\"event_type\", ip_version=\"ip_v\", sumby=\"src_ip\" | __error__=`` | event_type =~ `.+` | ip_version > 0 [$__range]))"
    }
   ]
  },
  {
   "title": "Potential Attacks by Destination",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(sumby) (count_over_time({app=\"suricata\", hostname=~\"$hostname\"} | json event_type=\"event_type\", ip_version=\"ip_v\", sumby=\"dest_ip\" | __error__=`` | event_type =~ `.+` | ip_version > 0 [$__range]))"
    }
   ]
  },
  {
   "title": "Potential Attacks by Destination Port",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(sumby) (count_over_time({app=\"suricata\", hostname=~\"$hostname\"} | json event_type=\"event_type\", ip_version=\"ip_v\", sumby=\"dest_port\" | __error__=`` | event_type =~ `.+` | ip_version > 0 [$__range]))"
    }
   ]
  },
  {
   "title": "Potential Attacks by Protocol",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(sumby) (count_over_time({app=\"suricata\", hostname=~\"$hostname\"} | json event_type=\"event_type\", ip_version=\"ip_v\", sumby=\"proto\" | __error__=`` | event_type =~ `.+` | ip_version > 0 [$__range]))"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"suricata\", hostname=~\"$hostname\"} | json event_type=\"event_type\", ip_version=\"ip_v\", class=\"alert.category\", priority=\"alert.severity\" | __error__=`` | event_type =~ `.+` | ip_version > 0"
    }
   ]
  },
  {
   "title": "Potential Attacks by Destination Locations",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(dest_ip, dst_location_latitude, dst_location_longitude) (count_over_time({app=\"suricata\", hostname=~\"$hostname\"} | json dest_ip=\"dest_ip\" | dst_location_latitude != `\"\"` | dst_location_longitude != `\"\"` [$__interval]))"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Event Logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"suricata\", hostname=~\"$hostname\"} | json | __error__=``"
    }
   ]
  }
 ]
}