name: Publish site to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Build
        run: hugo --minify
          
      - name: Deploy to Cloudflare Pages
        if: success()
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: d73a30412652351305e3f89fd125f690
          projectName: blog
          directory: public
          branch: main

      - uses: algolia/setup-algolia-cli@master
      - name: Upload Algolia Index
        run: algolia indices clear ${{ secrets.ALGOLIA_INDEX_NAME }} --confirm && algolia objects import ${{ secrets.ALGOLIA_INDEX_NAME }} --file public/index.json
        env:
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}