name: Publish site to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      HUGO_VERSION: 0.148.1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Build
        run: hugo --minify
          
      - name: Deploy to Cloudflare Pages
        if: success()
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=kre3-blog --branch main