name: Publish site to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Build
        run: hugo --minify
          
      - name: Deploy to Cloudflare Pages
        if: success()
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=kre3-blog --branch main

      - name: Upload Data # script from the hugo theme template
        run: |
          cp public/index.json themes/bilberry-hugo-theme/exampleSite/algolia/index.json
          cd themes/bilberry-hugo-theme/exampleSite/algolia
          npm install
          npm run data-upload -- -c \
            -f index.json \
            -a ${{ secrets.ALGOLIA_APP_ID }} \
            -k ${{ secrets.ALGOLIA_ADMIN_KEY }} \
            -n ${{ secrets.ALGOLIA_INDEX_NAME }}