name: Update Algolia search index

on:
  workflow_run:
    workflows: ["Publish site to GitHub Pages"]
    types:
      - completed

jobs:
  upload_algolia_index:
    runs-on: ubuntu-latest
    name: Update Algolia Index
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Upload Index
      uses: wangchucheng/algolia-uploader@master
      with:
        app_id: ${{ secrets.ALGOLIA_APP_ID }}
        admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        index_name: ${{ secrets.ALGOLIA_INDEX_NAME }}
        index_file_path: index.json
