name: Update Algolia search index

on:
  workflow_run:
    workflows: ["Publish site to GitHub Pages"]
    types:
      - completed

jobs:
  upload_algolia_index:
    runs-on: ubuntu-latest
    name: Update Algolia Index
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Setup Algolia Cli
      uses: algolia/setup-algolia-cli@master

    - name: Upload Index
      run: |
        algolia profile add --name "github-actions" --app-id ${{ secrets.ALGOLIA_APP_ID }} --admin-api-key ${{ secrets.ALGOLIA_ADMIN_KEY }} --default
        algolia objects import ${{ secrets.ALGOLIA_INDEX_NAME }} -F index.json --auto-generate-object-id-if-not-exist
